_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 55
            "2":
                - 1
                - 2
                - 3
                - 12
                - 55
            "3":
                - 2
                - 3
                - 14
                - 23
                - 34
                - 35
                - 55
            "4": 3.9.20
            "5": 0.19.4
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
n_steps:
    value: 3462
